# This file is auto-generated by Jekyll Auth
# Feel free to add additional Rake tasks so long as
# `rake assets:precompile` continues to generate the jekyll site

require 'html/proofer'
require 'find'

namespace :assets do
  task :precompile do
    sh "bundle exec jekyll-auth build"
  end
end

task :test do
  Rake::Task["assets:precompile"].execute
  tester = HTML::Proofer.new "./_site/", :href_ignore => ["https://github.com/github/government.github.com"]
  tester.run
end
