#!/usr/bin/env ruby

#fetches list of US repos from the social media registry, and outputs merged list to command line
#@todo, can this be done automagically without loosing formatting and comments?

require "open-uri"
require "json"
require "yaml"

org_file = YAML.load_file "./_data/organizations.yml"

orgs = JSON.parse open("http://registry.usa.gov/accounts?service_id=GitHub&format=json").read
orgs = orgs["accounts"].collect { |data| data["account"] }

orgs.each do |org|
  org_file["United States"].push(org.downcase) unless org_file["United States"].include?(org.downcase)
end

output = {
  "United States" => org_file["United States"].uniq.sort do
      |a,b| a.upcase <=> b.upcase
  end
}
puts "To be pasted into _data/organizations.yml"
puts output.to_yaml
