name: Ensure entries are alphabetized
permissions:
  contents: read

on:
  push:
    paths:
      - "Gemfile"
      - "script/alphabetize"
      - ".github/workflows/ensure-alphabetize.yml"
      - "_data/**"
  pull_request:
    paths:
      - "Gemfile"
      - "script/alphabetize"
      - ".github/workflows/ensure-alphabetize.yml"
      - "_data/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        bundler-cache: true
    - name: Ensure Orgs are sorted
      run: |
        bundle exec script/alphabetize
        git diff --color --exit-code
